### ISSUE TITLE
Classのお知らせのパースに失敗する

### ISSUE THREAD

**Issue by yumetodo** [huhugiter/TUS_CLASS#1]
# 再現手順

アプリを起動しログインしてホームのコンピュータ設備情報に行く。下の画像の一番上のメッセージをタップする

![a](https://file.qiitadon.com/media_attachments/files/002/636/256/original/bf908101d6ab04aa.png)

![b](https://file.qiitadon.com/media_attachments/files/002/636/255/original/6f3a2a308d3ee218.png)

# 環境

AQUOS zero2 Andorid 10 セキュリティーパッチレベル: 2020/04/01

**Comment by huhudev-git** [comment]
このバグは確かにこちらもあったことがある、まだ原因は不明だが、クラスは同時にひとつのページしか開けないから、アプリはそうしているが、完全に真似するのは難しいと思う、従って、時々このようになる。（もしこの規定に従っていない場合）

大きいな影響はないが、もう一回読み込めれば通常に入る。またもし知らせを読み込んだ後、新しい知らせが掲載されるとき、バグも発生するかもしれない、この辺の対応は難しいので、まだいいイディアがつかない

**Comment by huhudev-git** [comment]
ちなみにこのとき実際アクセスのページはこうなっている
![捕获](https://user-images.githubusercontent.com/26333129/82441470-e98a7480-9ad8-11ea-96af-9b502dd1e99b.PNG)

**Comment by yumetodo** [comment]
なるほど・・・

**Comment by huhudev-git** [comment]
<img width="367" alt="捕获12" src="https://user-images.githubusercontent.com/26333129/83961556-58384200-a8cf-11ea-9a5b-66096bff9701.PNG">

一応取得失敗、再試行の画面を表示する。
完全に修復するには恐らくページをアクセスするロジックをlow-levelで改善する可能性がある。
現時点でcloseする
